networks:
  web:
  ai:

services:
  open_webui:
    container_name: open_webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped

    networks:
      web:
      ai:

    volumes:
      - "{{ app_root }}/open_webui:/app/backend/data"

    environment:
      ENABLE_CHAT_RESPONSE_BASE64_IMAGE_URL_CONVERSION: true
      CHAT_STREAM_RESPONSE_CHUNK_MAX_BUFFER_SIZE: "7000000"

    labels:
      traefik.enable: true
      traefik.http.routers.chat.rule: Host(`chat.{{ tertiary_domain }}`)
      traefik.http.routers.chat.tls.certresolver: default
      traefik.http.services.chat.loadbalancer.server.port: 8080
      homepage.group: Admin
      homepage.name: AI chat
      homepage.icon: open-webui.png
      homepage.href: https://chat.{{ tertiary_domain }}/
      homepage.description: Open WebUI
      homepage.siteMonitor: http://chat:8080
      homepage.weight: 21

  ollama:
    container_name: ollama
    image: ollama/ollama:0.20.0
    restart: unless-stopped

    networks:
      web:
      ai:

    # environment:
    #   OLLAMA_DEBUG: "1"

    volumes:
      - "{{ app_root }}/ollama:/root/.ollama"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
