networks:
  web:
  changedetection:

services:
  changedetection:
    container_name: changedetection
    image: linuxserver/changedetection.io:latest
    restart: unless-stopped

    networks:
      - web
      - changedetection

    environment:
      PUID: 4004
      PGID: 4004
      BASE_URL: https://change.{{ tertiary_domain }}/
      # USE_X_SETTINGS: 1
      HIDE_REFERER: true
      LOGGER_LEVEL: WARNING
      PLAYWRIGHT_DRIVER_URL: ws://changedetection-chrome:3000/?stealth=1

    depends_on:
      changedetection-chrome:
        condition: service_started

    volumes:
      - "{{ app_root }}/changedetection:/config"

    labels:
      traefik.enable: true
      traefik.http.routers.change.rule: Host(`change.{{ tertiary_domain }}`)
      traefik.http.routers.change.tls.certresolver: default
      traefik.http.services.change.loadbalancer.server.port: 5000
      traefik.http.routers.change.middlewares: authelia
      homepage.group: Apps
      homepage.name: Change monitoring
      homepage.icon: changedetection-io.png
      homepage.href: https://change.{{ tertiary_domain }}/
      homepage.description: Changedetection.io
      homepage.siteMonitor: http://changedetection:5000
      homepage.weight: 40
      homepage.widget.type: changedetectionio
      homepage.widget.url: http://changedetection:5000
      homepage.widget.key: ${CHANGEDETECTION_API_KEY}

  changedetection-chrome:
    container_name: changedetection-chrome
    hostname: changedetection-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    user: 4004:4004

    restart: unless-stopped
    networks:
      - changedetection

    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1024
      SCREEN_DEPTH: 16
      ENABLE_DEBUGGER: false
      PREBOOT_CHROME: true
      CONNECTION_TIMEOUT: 300000
      MAX_CONCURRENT_SESSIONS: 10
      CHROME_REFRESH_TIME: 600000
      DEFAULT_BLOCK_ADS: true
      DEFAULT_STEALTH: true
      STATS_REFRESH_SECONDS: 86400
