networks:
  web:
  web_ext:

services:
  mc-survival:
    container_name: mc-survival
    image: itzg/minecraft-server
    restart: unless-stopped
    env_file:
      - minecraft.env

    networks:
      - web
      - web_ext

    volumes:
      - "{{app_root}}/games/minecraft/mc-survival-231223-1.21:/data"

    environment:
      TZ: {{ timezone }}
      EULA: True
      PVP: false
      DIFFICULTY: normal
      SERVER_NAME: Keelhaul Cay
      MEMORY: 1G
      MOTD: Keelhaul Cay
      TYPE: PAPER
      VERSION: 1.21.11

    labels:
      traefik.enable: false
