services:
  pangolin:
    image: fosrl/pangolin:latest
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - "{{ app_root }}/fossorial:/app/config"
    networks:
      - pangolin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15
    labels:
      use_traefik_instance: fossorial

  gerbil:
    image: fosrl/gerbil:latest
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy

    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - "{{ app_root }}/fossorial/:/var/config"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - "{{ public_ip }}:443:443"
      - "{{ public_ip }}:80:80"
      - "{{ public_ip }}:28361:28361"
      - "{{ public_ip }}:25569:25569"
    networks:
      - pangolin
      - docker-socket
    labels:
      use_traefik_instance: fossorial

  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil

    depends_on:
      pangolin:
        condition: service_healthy
      docker-socket-proxy:
        condition: service_started
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - "{{ app_root }}/fossorial/traefik:/etc/traefik:ro"
      - "{{ app_root }}/fossorial/letsencrypt:/letsencrypt"
    env_file: traefik.env
    labels:
      use_traefik_instance: fossorial

  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: lscr.io/linuxserver/socket-proxy:latest
    restart: unless-stopped

    environment:
      LOG_LEVEL: warning
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      POST: 0 # default, prevents making changes

    networks:
      - docker-socket

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  pangolin:
  docker-socket:
