---
- name: Reload udev
  command: udevadm control --reload
  changed_when: false

- name: Trigger udev
  command: udevadm trigger
  changed_when: false

- name: Reload systemd
  systemd:
    daemon_reload: true
