[rpool]
  use_template = prod
  # Using `recursive = zfs` makes the snapshots consistent, but precludes using `process_children_only`
  recursive = zfs

[bpool]
  use_template = boot
  recursive = zfs

[template_prod]
  autosnap = yes
  autoprune = yes
  frequently = 4
  hourly = 4
  daily = 7
  monthly = 6
  yearly = 0

[template_boot]
  autosnap = yes
  autoprune = yes
  frequently = 0
  hourly = 0
  daily = 7
  monthly = 6
  yearly = 0
