networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/23
          # Smaller than subnet size, so we can guarantee that there are addresses
          # outside of the "DHCP range" for containers that need fixed addresses
          # (just Traefik)
          ip_range: 172.18.0.0/24
          gateway: 172.18.0.1
  docker-socket:

services:
  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2
    restart: unless-stopped
    healthcheck:
      test: wget --spider --tries=1 http://localhost:2375/_ping || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21s"

    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      POST: 0 # default, prevents making changes

    networks:
      - docker-socket

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    container_name: traefik
    image: traefik:3.6
    restart: unless-stopped

    depends_on:
      docker-socket-proxy:
        condition: service_healthy

    ports:
      - 80:80
      - 443:443

    env_file:
      - traefik.env

    networks:
      web:
        # Some apps need to be able to depend on the IP of the trusted proxies
        # e.g. Nextcloud, which will refuse to look up a host via DNS
        # This IP is inside the subnet, but outside the ip_range to avoid
        # conflicts.
        ipv4_address: 172.18.1.1
      docker-socket:

    volumes:
      - "{{ app_root }}/traefik/traefik.yml:/traefik.yml"
      - "{{ app_root }}/traefik/dynamic_conf.yml:/dynamic_conf.yml"
      - "{{ app_root }}/traefik/acme.json:/acme.json"
      - /etc/localtime:/etc/localtime:ro

    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`proxy.{{ quinary_domain }}`)
      traefik.http.routers.api.entrypoints: https
      traefik.http.routers.api.tls.certresolver: default
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_USERS}
      # Below will cause Traefik to request a wildcard cert
      traefik.http.routers.api.tls.domains[0].main: "*.{{ quinary_domain }}"
      traefik.http.routers.api.tls.domains[0].sans: "{{ quinary_domain }}"

  landing_page:
    container_name: landing_page
    image: nginx:alpine
    networks:
      web:
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - "{{ app_root }}/landing_page/:/usr/share/nginx/html:ro"

    labels:
      traefik.enable: true
      traefik.http.routers.landing_page.rule: Host(`{{ quinary_domain }}`)
      traefik.http.routers.landing_page.tls.certresolver: default
      traefik.http.services.landing_page.loadbalancer.server.port: 80
      homepage.group: Admin
      homepage.name: Landing page
      homepage.icon: sh-airsonic
      homepage.href: https://{{ quinary_domain }}/
      homepage.siteMonitor: http://landing_page:80
      homepage.weight: 25
